version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - python --version
      - pip --version

  build:
    commands:
      - make install
      - make lint
      - make test